apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-on-k8s-admin.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
{{- toYaml .Values.sparkOnK8sAdmin | nindent 4 }}
