apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spark-on-k8s-admin.fullname" . }}-cr
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "scheduledsparkapplications"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-on-k8s-admin.fullname" . }}-crb
  namespace: {{ .Values.sparkOnK8sAdmin.spark.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-on-k8s-admin.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spark-on-k8s-admin.fullname" . }}-cr
