apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-on-k8s-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-on-k8s-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spark-on-k8s-admin.selectorLabels" . | nindent 4 }}
